export const sellerEndpointFields = [
  ["balance", "Balance endpoint", "/balance"],
  ["products", "Products endpoint", "/products"],
  ["product", "Single-product endpoint", "/products/{productKey}"],
  ["purchase", "Purchase endpoint", "/purchase"],
  ["orders", "Orders endpoint", "/orders"],
] as const;

export const sellerMappingFields = [
  ["products", "Product-list response path", "products"],
  ["product", "Single-product response path", "product"],
  ["order", "Purchase order response path", "order"],
  ["productKey", "Product key field", "productKey"],
  ["productName", "Product name field", "name"],
  ["productDescription", "Description field", "description"],
  ["productWarranty", "Warranty field", "warranty"],
  ["productPrice", "Product price field", "price"],
  ["productStock", "Product stock field", "stock"],
  ["productInStock", "Product in-stock field", "inStock"],
  ["variants", "Variants field", "variants"],
  ["variantKey", "Variant key field", "key"],
  ["variantName", "Variant name field", "name"],
  ["variantPrice", "Variant price field", "price"],
  ["variantStock", "Variant stock field", "stock"],
  ["variantInStock", "Variant in-stock field", "inStock"],
  ["requestProductKey", "Purchase request: product field", "productKey"],
  ["requestVariantKey", "Purchase request: variant field", "variantKey"],
  ["requestQuantity", "Purchase request: quantity field", "quantity"],
  ["orderId", "Order ID paths", "orderId,id"],
  ["orderRequested", "Requested quantity field", "requested"],
  ["orderFulfilled", "Fulfilled quantity field", "fulfilled"],
  ["orderItems", "Delivered items field", "items"],
  ["itemOrderId", "Delivered item order ID paths", "orderId,id"],
  ["itemFields", "Delivered fields array", "fields"],
  ["itemData", "Delivered data object", "data"],
  ["fieldName", "Delivery field name", "name"],
  ["fieldLabel", "Delivery field label", "label"],
  ["fieldValue", "Delivery field value", "value"],
  ["errorMessage", "Error message paths", "message,error"],
] as const;

export const quantumVaultDefaults = {
  providerName: "Quantum Vault",
  baseUrl: "https://www.quantumvault.me/api/v1",
  authHeader: "X-API-Key",
  authPrefix: "",
  endpoints: Object.fromEntries(sellerEndpointFields.map(([key, , value]) => [key, value])),
  mapping: Object.fromEntries(sellerMappingFields.map(([key, , value]) => [key, value])),
};
